### ISSUE TITLE
Fail hard when a backend fails to initialize, don't store the error return value in the backend repository

### ISSUE THREAD

**Issue by keichan34** [keichan34/exfile#15]
```
Server: localhost:4000 (http)
Request: POST /attachments/cache
** (exit) an exception was raised:
    ** (UndefinedFunctionError) undefined function :error.backend_mod/1 (module :error is not available)
        :error.backend_mod({:error, :enoent})
        (exfile) Exfile.Backend.upload/2
        (exfile) lib/exfile/router.ex:172: Exfile.Router.process_uploaded_file/3 
        (exfile) lib/exfile/router.ex:1: Exfile.Router.plug_builder_call/2
        (phoenix) lib/phoenix/router/route.ex:157: Phoenix.Router.Route.forward/4
        (my_app) lib/phoenix/router.ex:261: MyApp.Router.dispatch/2
        (my_app) web/router.ex:1: MyApp.Router.do_call/2
        (my_app) lib/my_app/endpoint.ex:1: MyApp.Endpoint.phoenix_pipeline/1
```

**Comment by keichan34** [comment]
This error occurs when `Exfile.Config.get_backend("backend name")` has a return value of `{:error, :enoent}`. In this case, it was the cache backend, so it was trying to make the cache directory and probably failed.
